### ISSUE TITLE
Board에서 file 컬럼을 제거한다

### ISSUE THREAD

**Issue by Sunkyoung-Yoon** [stockOneQ/back#103]
## Description 🖊️
Board에서 file 컬럼을 제거한다
## To-do 🧑‍💻
- [ ] Board에서 file 컬럼 제거
- [ ] file 관련 부분 수정
- [ ] Board 관련 테스트코드 수정

## ETC ➕
pm측을 통해 불필요한 컬럼인 것을 확인 -> 제거할 예정
