### ISSUE TITLE
매장, 기업, 제품, 비즈니스, 자료공유 엔티티 및 global config를 생성한다

### ISSUE THREAD

**Issue by Ji-Un-Gil** [stockOneQ/back#11]
## Description 🖊️
- 매장 및 기업, 제품, 비즈니스, 자료공유 엔티티를 생성한다
- global config 설정을 추가한다
  - EnumConverter, EnumStandard
  - BaseResponse, BaseResponseStatus

## To-do 🧑‍💻
- [ ] 매장 Store Entity
- [ ] 기업 Company Entity
- [ ] 제품 Product Entity
- [ ] 비즈니스 Business Entity
- [ ] 자료공유 Share Entity
