### ISSUE TITLE
슈퍼바이저의 사장님 연결 신청 API를 구현한다

### ISSUE THREAD

**Issue by chaeeerish** [stockOneQ/back#25]
## Description 🖊️
- 슈퍼바이저의 사장님 연결 신청 API를 구현한다

## To-do 🧑‍💻
- [ ] 슈퍼바이저 사장님 연결 신청 및 취소 API
- [ ] 슈퍼바이저 사장님 연결 삭제 API
- [ ] 테스트 코드 작성
