### ISSUE TITLE
코드 리팩토링을 진행한다

### ISSUE THREAD

**Issue by chaeeerish** [stockOneQ/back#51]
## Description 🖊️
- 코드 리팩토링을 진행한다

## To-do 🧑‍💻
- [ ] 폴더 구조 변경
- [ ] 필요없는 파일 제거
- [ ] 불필요한 코드 제거 및 수정
- [ ] 잘못된 테스트 코드 수정
- [ ] spring security 설정 수정
