### ISSUE TITLE
공통 예외에 대한 테스트 추가 및 Product API Test를 REST Docs에 연결, 공통 양식을 설정한다

### ISSUE THREAD

**Issue by Ji-Un-Gil** [stockOneQ/back#66]
## Description 🖊️
- Product API Test를 REST Docs에 연결하고 공통 양식을 설정한다
- Product API의 공통 예외에 대한 테스트 코드를 추가한다
## To-do 🧑‍💻
- [ ] ProductApiControllerTest - REST Docs로 API 명세서 생성
- [ ] 공통 양식 snippet 설정
- [ ] Product API의 공통 예외에 대한 테스트 코드 추가
