### ISSUE TITLE
게시글 및 댓글, 대댓글 엔티티를 생성한다

### ISSUE THREAD

**Issue by Sunkyoung-Yoon** [stockOneQ/back#7]
## Description 🖊️
* 게시글 및 댓글, 대댓글 엔티티를 생성한다
## To-do 🧑‍💻
- [ ] 게시글 Board Entity
- [ ] 댓글 Comment Entity
- [ ] 대댓글 ChildComment Entity
